# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_form.sizePolicy().hasHeightForWidth())
        login_form.setSizePolicy(sizePolicy)
        self.title_label = QtWidgets.QLabel(login_form)
        self.title_label.setGeometry(QtCore.QRect(150, 30, 100, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.password_edit = QtWidgets.QLineEdit(login_form)
        self.password_edit.setGeometry(QtCore.QRect(75, 149, 250, 25))
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.login_edit = QtWidgets.QLineEdit(login_form)
        self.login_edit.setGeometry(QtCore.QRect(75, 120, 250, 25))
        self.login_edit.setObjectName("login_edit")
        self.login_btn = QtWidgets.QPushButton(login_form)
        self.login_btn.setGeometry(QtCore.QRect(75, 190, 250, 28))
        self.login_btn.setObjectName("login_btn")

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Authorization"))
        self.title_label.setText(_translate("login_form", "Login"))
        self.password_edit.setPlaceholderText(_translate("login_form", "password"))
        self.login_edit.setPlaceholderText(_translate("login_form", "login"))
        self.login_btn.setText(_translate("login_form", "Login"))
