# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(320, 220)
        LoginForm.setMinimumSize(QtCore.QSize(320, 220))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(-1, -1, 20, -1)
        self.formLayout.setObjectName("formLayout")
        self.login_label = QtWidgets.QLabel(LoginForm)
        self.login_label.setObjectName("login_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.login_label)
        self.login_le = QtWidgets.QLineEdit(LoginForm)
        self.login_le.setMaxLength(255)
        self.login_le.setObjectName("login_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_le)
        self.password_label = QtWidgets.QLabel(LoginForm)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_le = QtWidgets.QLineEdit(LoginForm)
        self.password_le.setMaxLength(255)
        self.password_le.setFrame(True)
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setObjectName("password_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_le)
        self.login_btn = QtWidgets.QPushButton(LoginForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setObjectName("login_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.login_btn)
        self.verticalLayout_2.addLayout(self.formLayout)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Login"))
        self.login_label.setText(_translate("LoginForm", "Login:"))
        self.password_label.setText(_translate("LoginForm", "Password:"))
        self.login_btn.setText(_translate("LoginForm", "Sign in"))
