# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'get_date_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_get_date_form(object):
    def setupUi(self, get_date_form):
        get_date_form.setObjectName("get_date_form")
        get_date_form.resize(230, 160)
        get_date_form.setMinimumSize(QtCore.QSize(230, 160))
        get_date_form.setMaximumSize(QtCore.QSize(230, 160))
        self.verticalLayout = QtWidgets.QVBoxLayout(get_date_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(get_date_form)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.month_combo_box = QtWidgets.QComboBox(get_date_form)
        self.month_combo_box.setObjectName("month_combo_box")
        self.verticalLayout.addWidget(self.month_combo_box)
        self.year_spin_box = QtWidgets.QSpinBox(get_date_form)
        self.year_spin_box.setObjectName("year_spin_box")
        self.verticalLayout.addWidget(self.year_spin_box)
        self.create_report_btn = QtWidgets.QPushButton(get_date_form)
        self.create_report_btn.setObjectName("create_report_btn")
        self.verticalLayout.addWidget(self.create_report_btn)

        self.retranslateUi(get_date_form)
        QtCore.QMetaObject.connectSlotsByName(get_date_form)

    def retranslateUi(self, get_date_form):
        _translate = QtCore.QCoreApplication.translate
        get_date_form.setWindowTitle(_translate("get_date_form", "Укажите дату"))
        self.title.setText(_translate("get_date_form", "Укажите месяц и год отчета"))
        self.create_report_btn.setText(_translate("get_date_form", "Создать отчет"))
