# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(300, 150))
        Form.setMaximumSize(QtCore.QSize(400, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icons/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.host_label = QtWidgets.QLabel(Form)
        self.host_label.setObjectName("host_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.host_label)
        self.host_le = QtWidgets.QLineEdit(Form)
        self.host_le.setObjectName("host_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.host_le)
        self.port_label = QtWidgets.QLabel(Form)
        self.port_label.setObjectName("port_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.port_label)
        self.port_le = QtWidgets.QLineEdit(Form)
        self.port_le.setInputMethodHints(QtCore.Qt.ImhNone)
        self.port_le.setObjectName("port_le")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.port_le)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_btn = QtWidgets.QPushButton(Form)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки соединения"))
        self.host_label.setText(_translate("Form", "IP адрес"))
        self.port_label.setText(_translate("Form", "Порт"))
        self.cancel_btn.setText(_translate("Form", "Отмена"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
